// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bldnunrindnyherziwlt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsZG51bnJpbmRueWhlcnppd2x0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwMDUwMjUsImV4cCI6MjA3NTU4MTAyNX0.vYL1Qr4K7QE9_02JqxsbsZNdmOTWoV52KWbM-_4LFIA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});